version: "3"

services:
  insta-follower-notifier:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: "insta-follower-notifier"
    volumes:
      - ../.:/app
    env_file:
      - ../.env.test
    ports:
      - 8190:80
    networks:
      - insta

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - insta

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - insta

networks:
  insta:
    external:
      name: docker_insta

volumes:
  redis_data: