version: "3"

services:
  insta-follower-notifier:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: "insta-follower-notifier"
    volumes:
      - ../.:/app
    env_file:
      - ../.env.test
    ports:
      - 8190:80
    networks:
      - qa_net

#  redis:
#    image: "redis:alpine"
#    hostname: redis
#    command: redis-server
#    ports:
#      - "6380:6379"
#    volumes:
#      - $PWD/redis-data:/var/lib/redis
#    environment:
#      - REDIS_REPLICATION_MODE=master
#    networks:
#      - qa_net

#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    environment:
#      - REDIS_HOSTS=local:redis:6379
#    ports:
#      - "8081:8081"
#    networks:
#      - qa_net

networks:
  qa_net:
    external:
      name: docker_qa_net